from __future__ import annotations

import datetime as dt
import json
import os
import urllib.request
from collections import Counter
from pathlib import Path
from typing import Any


USERNAME = os.environ.get("GITHUB_USERNAME", "TomLo-FStack")
TOKEN = os.environ.get("GITHUB_TOKEN", "")
ROOT = Path(__file__).resolve().parents[1]


def github_json(url: str) -> Any:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": f"{USERNAME}-profile-readme-generator",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"

    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def public_repos() -> list[dict[str, Any]]:
    repos: list[dict[str, Any]] = []
    page = 1
    while True:
        url = (
            f"https://api.github.com/users/{USERNAME}/repos"
            f"?type=owner&sort=pushed&direction=desc&per_page=100&page={page}"
        )
        chunk = github_json(url)
        if not chunk:
            break
        repos.extend(chunk)
        page += 1
    return repos


def text(value: Any, fallback: str = "") -> str:
    if value is None:
        return fallback
    value = str(value).strip()
    return value if value else fallback


def language_name(repo: dict[str, Any]) -> str:
    language = repo.get("language")
    return text(language, "Mixed")


def repo_line(repo: dict[str, Any]) -> str:
    name = repo["name"]
    url = repo["html_url"]
    desc = text(repo.get("description"), "No description yet.")
    language = language_name(repo)
    stars = repo.get("stargazers_count", 0)
    forks = repo.get("forks_count", 0)
    pushed = text(repo.get("pushed_at"), "")
    pushed_day = pushed[:10] if pushed else "unknown"
    fork_badge = " fork" if repo.get("fork") else ""
    return (
        f"- [{name}]({url})"
        f" - {desc}"
        f" | `{language}` | stars `{stars}` | forks `{forks}` | pushed `{pushed_day}`{fork_badge}"
    )


def project_table(repos: list[dict[str, Any]]) -> str:
    featured = [repo for repo in repos if not repo.get("fork")][:6]
    if not featured:
        featured = repos[:6]

    cells: list[str] = []
    for repo in featured:
        name = repo["name"]
        url = repo["html_url"]
        desc = text(repo.get("description"), "No description yet.")
        language = language_name(repo)
        stars = repo.get("stargazers_count", 0)
        forks = repo.get("forks_count", 0)
        cells.append(
            "<td width=\"50%\" valign=\"top\">\n"
            f"<a href=\"{url}\"><strong>{name}</strong></a><br/>\n"
            f"<span>{desc}</span><br/><br/>\n"
            f"<code>{language}</code> &nbsp; stars <code>{stars}</code> &nbsp; forks <code>{forks}</code>\n"
            "</td>"
        )

    rows: list[str] = []
    for i in range(0, len(cells), 2):
        left = cells[i]
        right = cells[i + 1] if i + 1 < len(cells) else "<td width=\"50%\"></td>"
        rows.append(f"<tr>\n{left}\n{right}\n</tr>")
    return "<table>\n" + "\n".join(rows) + "\n</table>"


def language_bar(counter: Counter[str]) -> str:
    if not counter:
        return "`No language data yet.`"

    total = sum(counter.values())
    parts: list[str] = []
    for language, count in counter.most_common(8):
        pct = round(count * 100 / total)
        parts.append(f"`{language}` {pct}%")
    return " &nbsp; ".join(parts)


def render(repos: list[dict[str, Any]], user: dict[str, Any]) -> str:
    public = [repo for repo in repos if not repo.get("private")]
    source_repos = public or repos
    languages = Counter(language_name(repo) for repo in source_repos)
    total_stars = sum(repo.get("stargazers_count", 0) for repo in source_repos)
    total_forks = sum(repo.get("forks_count", 0) for repo in source_repos)
    updated = dt.datetime.now(dt.UTC).strftime("%Y-%m-%d %H:%M UTC")
    display_name = text(user.get("name"), USERNAME)
    bio = text(user.get("bio"), "Systems builder focused on data structures, language experiments, and fast tooling.")

    recent = "\n".join(repo_line(repo) for repo in source_repos[:8])
    if not recent:
        recent = "- Building in public soon."

    return f"""<!-- AUTO-GENERATED by scripts/build_readme.py. Edit the script, not this file. -->

<h1 align="center">{display_name}</h1>

<p align="center">
  <img src="https://readme-typing-svg.demolab.com?font=JetBrains+Mono&weight=700&size=22&duration=2500&pause=700&center=true&vCenter=true&width=820&lines=Data+Structures+%2F+Systems+Programming;Mojo+%2F+V+%2F+C+%2F+Elixir+experiments;Build+fast%2C+measure+honestly%2C+ship+clean" alt="typing intro" />
</p>

<p align="center">
  <a href="https://github.com/{USERNAME}?tab=repositories"><img alt="Repos" src="https://img.shields.io/badge/public_repos-{len(source_repos)}-0f172a?style=for-the-badge&labelColor=111827"></a>
  <img alt="Stars" src="https://img.shields.io/badge/stars-{total_stars}-f59e0b?style=for-the-badge&labelColor=111827">
  <img alt="Forks" src="https://img.shields.io/badge/forks-{total_forks}-38bdf8?style=for-the-badge&labelColor=111827">
  <img alt="Updated" src="https://img.shields.io/badge/auto_update-{updated.replace(' ', '_')}-22c55e?style=for-the-badge&labelColor=111827">
</p>

## Mission Control

{bio}

I like projects where correctness and speed can both be inspected: data-structure workloads, language runtimes, CLI drills, and benchmark harnesses.

```text
focus      :: data structures | systems languages | benchmark tooling
current    :: building compact, testable implementations across languages
principle  :: small surface area, clear measurement, reproducible setup
```

## Project Radar

{project_table(source_repos)}

## Language Signal

{language_bar(languages)}

## Live Telemetry

<p align="center">
  <img height="165" src="https://github-readme-stats.vercel.app/api?username={USERNAME}&show_icons=true&theme=tokyonight&hide_border=true&include_all_commits=true&rank_icon=github" alt="GitHub stats" />
  <img height="165" src="https://github-readme-stats.vercel.app/api/top-langs/?username={USERNAME}&layout=compact&theme=tokyonight&hide_border=true&langs_count=8" alt="Top languages" />
</p>

<p align="center">
  <img src="https://github-profile-trophy.vercel.app/?username={USERNAME}&theme=tokyonight&no-frame=true&no-bg=true&margin-w=8&row=1" alt="GitHub trophies" />
</p>

<p align="center">
  <img src="https://github-readme-activity-graph.vercel.app/graph?username={USERNAME}&theme=tokyo-night&hide_border=true&area=true" alt="Contribution activity graph" />
</p>

## Latest Public Pushes

{recent}

## Automation

This profile README updates itself from GitHub Actions. The workflow reads public repository metadata, rebuilds this page, and commits the diff when anything changes.

<sub>Last generated: {updated}</sub>
"""


def main() -> None:
    user = github_json(f"https://api.github.com/users/{USERNAME}")
    repos = public_repos()
    (ROOT / "README.md").write_text(render(repos, user), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
